### ISSUE TITLE
I write a framework like Effects in only 700+ lines of codes

### ISSUE THREAD

**Issue by sxysxy** [Microsoft/FX11#11]
https://github.com/sxysxy/HfEngine/blob/master/Loader/libruby/HFSF.rb 
example using it.
https://github.com/sxysxy/HfEngine/blob/master/Loader/libruby/Graphics2D/Renderer.rb

Document(unfinished):
https://github.com/sxysxy/HfEngine/blob/master/Document/HFSF_DSL.md

**Comment by walbourn** [comment]
Since this is Ruby code, I'd recommend advertising this on the project that provides the DirectX interop from Ruby that you rely on.

**Comment by sxysxy** [comment]
Yes. well, as you can see, I have made a project that provides the DirectX interop from Ruby and use this shaders framework in it -- In fact, To realize that DSL only costs about 200 lines codes, the rest parts are runtime support(these part rely on 'the project'), which creates and manages the resources and help set rendering state.

Not for advertising, I am a senior high school student, because of the Olympic Information I have chance to use computer frequently in school.
And I like Microsoft. :)
