### ISSUE TITLE
How to set StencilRef

### ISSUE THREAD

**Issue by eclazi** [Microsoft/FX11#8]
Is there anyway to set the StencilRef value?

It seems its only possible to set the depth stencil state...

**Comment by walbourn** [comment]
The ``StencilRef`` value is part of the pass description:

    technique11 RenderSceneWithTexture1Light
    {
        pass P0
        {
            SetVertexShader( CompileShader( vs_4_0_level_9_1, RenderSceneVS( 1, true, true ) ) );
            SetGeometryShader( NULL );
            SetPixelShader( CompileShader( ps_4_0_level_9_1, RenderScenePS( true ) ) );

            SetDepthStencilState( EnableDepth, 0 /* StencilRef goes here */ );
        }
    }
